### ISSUE TITLE
Work with Jacoco on Gradle

### ISSUE THREAD

**Issue by youdidut** [bjoernQ/unmock-plugin#12] opened 2015-08-16 18:02 UTC
Hi, I am interested in getting the coverage report on Android libraries. That is why I need this unmock plugin to avoid using mockable-android.jar. However, after implementing the plugin, my application does not import the class files in unmock_work directory. It is still importing the old,mocked ones. I know this for sure because I can see the class IDs in the jacoco report. 
Do you have any idea why this is happening? How can you prove that the application now is importing the unmocked classes instead of the mocked ones?

**Comment by bjoernQ** [comment] 2015-08-17 05:25
Not sure I understand the issue correctly. The framework classes shouldn't show up in the coverage report at all (no matter where they are loaded from at runtime - mockable-android-X.jar or unmocked-android.jar)

The shouldn't be instrumented - it's also a good idea to exclude generated classes and other libraries e.g. support library etc.

Maybe you can share some code (an example project if your code isn't open source) to reproduce the issue.

Don't think it's actually an issue with the plugin but an configuration issue (as far as I understand the problem).

**Comment by youdidut** [comment] 2015-08-17 14:01
Hi, Björn!

I have uploaded the project in dropbox. You could follow the instruction in ReadMe to reproduce the issue:
https://www.dropbox.com/s/0jrczgi34k5pjqq/test-jacoco.tar.gz?dl=0

When you click sessions on the right-top cornor in the Jacoco report, you can see all the classes that are collected execution data for, which includes android.graphics.Bitmap from the graphics library. Since only instrumented class can be used to collect execution data, I believe Bitmap.class is instrumented. As long as the same Bitmap.class is provided, the report can be generated correctly. I won't be able to get the report with mockable-android-22.jar, since it changes the class id of Bitmap.class according to http://www.eclemma.org/jacoco/trunk/doc/classids.html 'What can cause different class ids?'.

I have included all three parts in your instruction to configure the plugin, and I also set the unmocked Bitmap.class as the classDirectory to generate the report. If jacoco did instrumented this file, use it to run tests, I should be able to see the coverage report for Bitmap.class.

During the report generation phase, you could see the warning:
[ant:jacocoReport] Classes in bundle 'app' do no match with execution data. For report generation the same class files must be used as at runtime.
[ant:jacocoReport] Execution data for class android/graphics/Bitmap does not match.

Thank you very much. I really hope your plugin can help me get the report.

**Comment by bjoernQ** [comment] 2015-08-18 05:24
Unfortunately the projects doesn't build on my system. However I don't really understand the your project setup.

You tests use Robolectric. My plugin isn't designed to work with Robolectric.

Additionally the Jacoco closure instruments classes under build/intermediates/unmock_work/

I don't really understand why you want to instrument the framework classes. You should instrument all the classes in build/intermediates/classes/<buildtype/flavor>/

Additionally when running the tests the classes will be loaded from unmocked-android.jar - not the working directory.

Since my plugin won't help you with Robolectric tests I'll close this issue.

Maybe you should ask the Robolectric project for help with coverage when using this approach.

**Closed by bjoernQ** 2015-08-18 05:24 UTC
