### ISSUE TITLE
Classes not mocked with Kotlin

### ISSUE THREAD

**Issue by SpaceBison** [bjoernQ/unmock-plugin#58] opened 2019-05-10 06:00 UTC
This might be related to #56.
Using Unmock with Kotlin does not seem to work.

Example to reproduce:

- UnMock 7.3
- Kotlin 1.3.31
- Gradle 5.1.1
- Android Gradle plugin 3.4.0

Project level build.gradle buildscript block:

    buildscript {
        ext.kotlin_version = '1.3.31'
        repositories {
            google()
            jcenter()
            
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.4.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'de.mobilej.unmock:UnMockPlugin:0.7.3'
        }
    }

Example test to reproduce:

    class ExampleTest {
    
        @Test
        fun test() {
            assertTrue(Looper.getMainLooper().isCurrentThread)
        }
    }

Result:

    java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.
    
    at android.os.Looper.getMainLooper(Looper.java)
    at com.example.unmockkotlin.RegularTest.addition_isCorrect(RegularTest.kt:11)

**Comment by bjoernQ** [comment] 2019-05-11 13:03
Hi,

by default only a small portion of the SDK is "unmocked". You could configure which classes you want but in this case `Looper` uses other classes e.g. `MessageQueue` which call into native code. This won't work.

You could:
- mock these classes yourself with a strong mocking framework e.g. MockK
- try using Robolectric: Robolectric tries to emulate most of the SDK (in opposite to this project)

Hope this helps.

Closing this because it works as designed

**Closed by bjoernQ** 2019-05-11 13:03 UTC

**Comment by calvarez-ov** [comment] 2020-04-06 10:13
I came here looking for any info about `mockk` being used in conjuction with `UnmockPlugin`.

I only use mockk and was hoping to remove some of my mockk code by using UnmockPlugin instead, but I'm running into issues where mockk, which previously worked, is now broken.  I don't have a sample project to share. I can provide more info if needed. But before getting too deep into this, I was wondering if there is already some known limitations making these two tools not work with each other.

**Comment by bjoernQ** [comment] 2020-04-08 16:41
Thanks for the update! Good to hear Mockito solves the problem

I think I used the plug-in with mockk before but I should try it again to see if I can improve anything
